version: '3.1'
services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    volumes:
      - "./server/src:/app/src"
    ports:
      - "8081:8081"
    depends_on:
      - postgresql
  client:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    volumes:
      - "./client/src:/app/src"
    ports:
      - "8080:8080"
    depends_on:
      - postgresql
      - server
  postgresql:
    command: postgresql
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    logging:
      driver: none
